timeout: 5
serial: yes
serial_baudrate: 115200

/OkraLinux LiveCD
    protocol: linux
    kernel_path: boot():/boot/vmlinuz
    module_path: boot():/boot/initramfs-live.img
    cmdline: console=tty0 nomodeset audit=0 systemd.show_status=false rd.live.image
