timeout: 5
serial: yes
serial_baudrate: 115200

/OkraLinux Base OS 0
    protocol: linux
    kernel_path: boot():/boot/vmlinuz
    module_path: boot():/boot/initramfs-live.img
    cmdline: console=tty0 console=ttyS0,115200n8 nomodeset loglevel=6 systemd.show_status=yes systemd.status_unit_format=name systemd.debug-shell=0 audit=0 rd.live.image
